[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=15552000"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=15552000"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"
